package com.contlo.androidsdk.utils

object Constants {
    const val PREFERENCE_NAME = "contlosdk"
    const val EMAIL = "email"
    const val PHONE_NUMBER = "phone_number"
    const val API_KEY = "API_KEY"
    const val FCM_TOKEN = "FCM_TOKEN"
    const val MOBILE_PUSH_CONSENT = "MOBILE_PUSH_CONSENT"
    const val AD_ID = "AD_ID"
    const val PACKAGE_NAME = "PACKAGE_NAME"
    const val APP_NAME = "APP_NAME"
    const val APP_VERSION = "APP_VERSION"
    const val MODEL_NAME = "MODEL_NAME"
    const val MANUFACTURER = "MANUFACTURER"
    const val NETWORK_TYPE = "NETWORK_TYPE"
    const val EXTERNAL_ID = "EXTERNAL_ID"
    const val API_LEVEL = "API_LEVEL"
    const val OS_TYPE = "OS_TYPE"
    const val OS_VERSION = "OS_VERSION"
    const val SOURCE = "SOURCE"
    const val SDK_VERSION = "SDK_VERSION"
    const val DEVICE_EVENT_TIME = "DEVICE_EVENT_TIME"
    const val TIMEZONE = "TIMEZONE"
    const val NEW_APP_INSTALL = "NEW_APP_INSTALL"
    const val AD_ID_FCM_FOUND = "AD_ID_FCM_FOUND"
    const val PUSH_CONSENT_FCM_FOUND = "PUSH_CONSENT_FCM_FOUND"
}